### PR TITLE
fix(angular-query-devtools) non optional devtools property in devtool…

### PR DESCRIPTION
**Pull request by ducin**
Moved things around in order to remove optionality and unnecessary optional chaining.
Devtools testes, example is working.

### CODE REVIEW

**Comment by ducin** [comment]
That's odd, 30 tests failing in the Nx Cloud build all relate to **solid query**. @arnoud-dv do you get similar errors?

**Comment by ducin** [comment]
Just to make sure I didn't introduce any regression I ran `npm run test:ci` on `feature/angular-query` **without** above changes and I get this:

```

 >  NX   Ran targets test:format, test:eslint, test:lib, test:types, test:build, test:bundle, build for 33 projects (19s)
 
    ✔    107/114 succeeded [103 read from cache]
 
    ✖    7/114 targets failed, including the following:
         - nx run @tanstack/angular-query-experimental:test:types
         - nx run @tanstack/svelte-query-devtools:test:types
         - nx run @tanstack/angular-query-devtools-experimental:test:lib
         - nx run @tanstack/angular-query-experimental:test:eslint
         - nx run angular-vite:test:bundle
         ...and 2 more...
 ```

When it comes to tests, I hope npm/pnpm doesn't make a difference...

Anyway, I'm curious @arnaud-dv if you tried to run those when trying to merge into tanstack repo.

**Comment by ducin** [comment]
# Triage

- `@tanstack/angular-query-devtools-experimental:"test:lib"` - it's basically missing test files.
- `@tanstack/angular-query-experimental:"test:types"` - (single?) compilation error, `Type 'void' is not assignable to type 'Promise<unknown>'.`
- `nx run @tanstack/angular-query-experimental:"test:eslint"` - linter: `5 problems (5 errors, 0 warnings) / 4 errors and 0 warnings potentially fixable with the `--fix` option.`
- `nx run angular-vite:"test:bundle"` - `[vite]: Rollup failed to resolve import "rxjs" from ".../angular-query-experimental/build/node_modules/@angular/core/fesm2022/core.mjs". / This is most likely unintended because it can break your application at runtime.` - this looks rather important 🔥

arnoud-dv I can take care of first 3 straight ahead, if you haven't done that locally

----

## `@tanstack/angular-query-devtools-experimental:"test:lib"`

```
> nx run @tanstack/angular-query-devtools-experimental:"test:lib"

> @tanstack/angular-query-devtools-experimental@5.4.3 test:lib /Users/tomaszducin/Development/contrib/query/packages/angular-query-devtools-experimental
> vitest run --coverage
 RUN  v0.34.6 /Users/tomaszducin/Development/contrib/query/packages/angular-query-devtools-experimental
      Coverage enabled with istanbul
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1
 ELIFECYCLE  Command failed with exit code 1.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:lib for project @tanstack/angular-query-devtools-experimental and 3 task(s) they depend on (7s)
 
    ✖    1/4 failed
    ✔    3/4 succeeded [2 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/z2FDmYZ6zA
```
----
## `@tanstack/angular-query-experimental:"test:types"`
```
> nx run @tanstack/angular-query-experimental:"test:types"

> @tanstack/angular-query-experimental@5.4.3 test:types /Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental
> tsc



src/tests/injectMutation.test.ts(40,9): error TS2322: Type '() => void' is not assignable to type 'MutationFunction<unknown, void>'.
  Type 'void' is not assignable to type 'Promise<unknown>'.
src/tests/injectMutation.test.ts(46,23): error TS2345: Argument of type '{ par1: string; }' is not assignable to parameter of type 'void'.
 ELIFECYCLE  Command failed with exit code 2.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:types for project @tanstack/angular-query-experimental and 1 task(s) they depend on (2s)
 
    ✖    1/2 failed
    ✔    1/2 succeeded [1 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/RuOyF5BKvy
```
----
## `@tanstack/angular-query-experimental:"test:eslint"`
```
> nx run @tanstack/angular-query-experimental:"test:eslint"

> @tanstack/angular-query-experimental@5.4.3 test:eslint /Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental
> eslint --ext .ts,.tsx ./src
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/src/injectQueryClient.ts
  2:1  error  `ngxtension/create-injection-token` import should occur before type import of `@tanstack/query-core`  import/order

/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/src/query-proxy.ts
   1:20  error  Member 'Signal' of the import declaration should be sorted alphabetically   sort-imports
   3:1   error  All imports in the declaration are only used as types. Use `import type`    @typescript-eslint/consistent-type-imports
   3:1   error  `./types` import should occur before type import of `@tanstack/query-core`  import/order
  19:11  error  Unnecessary conditional, value is always truthy                             @typescript-eslint/no-unnecessary-condition

✖ 5 problems (5 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.

 ELIFECYCLE  Command failed with exit code 1.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:eslint for project @tanstack/angular-query-experimental and 1 task(s) they depend on (4s)
 
    ✖    1/2 failed
    ✔    1/2 succeeded [1 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/sGVhzi99Jp
```

----
`@tanstack/angular-query-experimental:"test:eslint"`

```
> nx run @tanstack/angular-query-experimental:"test:eslint"

> @tanstack/angular-query-experimental@5.4.3 test:eslint /Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental
> eslint --ext .ts,.tsx ./src
DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/src/injectQueryClient.ts
  2:1  error  `ngxtension/create-injection-token` import should occur before type import of `@tanstack/query-core`  import/order

/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/src/query-proxy.ts
   1:20  error  Member 'Signal' of the import declaration should be sorted alphabetically   sort-imports
   3:1   error  All imports in the declaration are only used as types. Use `import type`    @typescript-eslint/consistent-type-imports
   3:1   error  `./types` import should occur before type import of `@tanstack/query-core`  import/order
  19:11  error  Unnecessary conditional, value is always truthy                             @typescript-eslint/no-unnecessary-condition

✖ 5 problems (5 errors, 0 warnings)
  4 errors and 0 warnings potentially fixable with the `--fix` option.

 ELIFECYCLE  Command failed with exit code 1.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:eslint for project @tanstack/angular-query-experimental and 1 task(s) they depend on (4s)
 
    ✖    1/2 failed
    ✔    1/2 succeeded [1 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/sGVhzi99Jp
```
----
## `angular-vite:test:bundle`
```
Mac-Mini-Tomaszku~/Development/contrib/query[feature/angular-query|⚑1] % nx run angular-vite:test:bundle

   ✔    4/4 dependent project tasks succeeded [1 read from cache]

   Hint: you can run the command with --verbose to see the full dependent project outputs

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————


> nx run angular-vite:"test:bundle"

> angular-vite@ test:bundle /Users/tomaszducin/Development/contrib/query/integrations/angular-vite
> vite build
vite v4.5.0 building for production...
transforming...
✓ 14 modules transformed.
✓ built in 858ms
[vite]: Rollup failed to resolve import "rxjs" from "/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/build/node_modules/@angular/core/fesm2022/core.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "rxjs" from "/Users/tomaszducin/Development/contrib/query/packages/angular-query-experimental/build/node_modules/@angular/core/fesm2022/core.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.0_less@4.2.0_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onRollupWarning (file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.0_less@4.2.0_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48248:9)
    at onwarn (file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/vite@4.5.0_@types+node@18.18.0_less@4.2.0_sass@1.69.5_terser@5.24.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file:///Users/tomaszducin/Development/contrib/query/node_modules/.pnpm/rollup@3.29.4/node_modules/rollup/dist/es/shared/node-entry.js:24822:26
 ELIFECYCLE  Command failed with exit code 1.

 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target test:bundle for project angular-vite and 4 task(s) they depend on (11s)
 
    ✖    1/5 failed
    ✔    4/5 succeeded [1 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/8BF5ipPUcV
```

**Comment by arnoud-dv** [comment]
Pushed some eslint and other small fixes. Also downgraded vitest, Solid tests don't succeed on newer vitest.

**Comment by ducin** [comment]
Rebased to your update. I'll take care of prettier.

But now we've got a svelte fail. Is there a possibility to merge it to feature/angular-query and take care of other things there @arnoud-dv as they're unrelated to this PR?

I guess if you're directly pushing to the `feature/angular-query` branch without CI checks (`npm run test:ci`) the code doesn't go through all the checks... at least it looks like this.

**Comment by arnoud-dv** [comment]
Aligned some versions, updated Vite to 4.5.0 as vite-plugin-solid depends on 4.5.0 and Svelte was using types from both 4.5.0 and 4.4.11, giving the error there. Also removed the Angular Vite application in /integrations as I don't want another Vite version appearing from a plugin. Solid tests are failing inconsistently. Sometimes when re-running after failure they'll succeed. It looks like actual timers are used, not mocked.

**Comment by ducin** [comment]
@arnoud-dv finally passing 😍! could you take a look?

**Pull request closed without merging**
